apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: opentelemetrycompositeworkloads.gitops.bluesolution.es
spec:
  group: gitops.bluesolution.es
  names:
    kind: OpentelemetryCompositeWorkload
    plural: opentelemetrycompositeworkloads
  claimNames:
    kind: OpentelemetryWorkload
    plural: opentelemetryworkloads
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string