apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: questdbcompositeworkloads.kubernetes.gitops.bluesolution.es
spec:
  compositeTypeRef:
    apiVersion: gitops.bluesolution.es/v1alpha1
    kind: QuestdbCompositeWorkload
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: questdbNamespace
            base:
              apiVersion: kubernetes.crossplane.io/v1
              kind: Object
              metadata:
                name: questdb-namespace
                namespace: default
              spec:
                patches:
                  - fromFieldPath: "spec.label.questdbNamespace"
                    toFieldPath: "spec.forProvider.manifest.metadata.namespace"
                    policy:
                      fromFieldPath: "Required"
                providerConfigRef:
                  name: kubernetes-provider
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: Namespace
                    metadata:
                      name: questdb
            # Tells crossplante to create a QuestDB custom resource from the questdb kubernetes operator in the questdb namespace
          - name: questdbSingleLocal
            base:
              apiVersion: kubernetes.crossplane.io/v1
              kind: Object
              metadata:
                name: questdb-instance
                namespace: default
              spec:
                patches:
                  - fromFieldPath: "spec.label.questdbNamespace"
                    toFieldPath: "spec.forProvider.manifest.metadata.namespace"
                    policy:
                      fromFieldPath: "Required"
                providerConfigRef:
                  name: kubernetes-provider
                forProvider:
                  manifest:
                    apiVersion: crd.questdb.io/v1beta1
                    kind: QuestDB
                    metadata:
                      name: questdb-single-local
                      namespace: questdb
                      labels:
                        app.kubernetes.io/name: questdb
                        app.kubernetes.io/instance: questdb-single-local
                        app.kubernetes.io/part-of: questdb-operator
                        app.kubernetes.io/managed-by: crossplane
                        app.kubernetes.io/created-by: questdb-operator
                    spec:
                      replicas: 1
                      imagePullPolicy: Always
                      image: questdb/questdb:8.2.1
                      volume:
                        size: 20Gi
