apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: questdbcompositeworkloads.gitops.bluesolution.es
spec:
  group: gitops.bluesolution.es
  names:
    kind: QuestdbCompositeWorkload
    plural: questdbcompositeworkloads
  claimNames:
    kind: QuestdbWorkload
    plural: questdbworkloads
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                label:
                  type: object
                  properties:
                    questdbNamespace:
                      type: string  
