apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: nodeexportercompositeworkloads.gitops.bluesolution.es
spec:
  group: gitops.bluesolution.es
  names:
    kind: NodeExporterCompositeWorkload
    plural: nodeexportercompositeworkloads
  claimNames:
    kind: NodeExporterWorkload
    plural: nodeexporterworkloads
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string